### ISSUE TITLE
Ability to get listing information for a particular agent

### ISSUE THREAD

**Issue by jbardnz** [tugkan/realtor-scraper#3]
Hey there,

I was wondering if you would consider add the ability to use agent profile urls as start urls. 

E.g. I want to get all of the listings for a particular agent: https://www.realtor.com/realestateagents/5a28883df695ab0010dfe28b

Cheers

**Comment by tugkan** [comment]
Hey @jbardnz ,

Thank you very much for using our product. We just updated the public actor to retrieve the information from the agent profile URLs. You can use the latest version to retrieve the results.

Best
