### ISSUE TITLE
Scraping pages with a large number of properties skips 25% of the listings

### ISSUE THREAD

**Issue by jakekrafczyk** [tugkan/realtor-scraper#4]
When using startURL "https://www.realtor.com/realestateandhomes-search/Texas/type-land/price-na-19999" it scraped 2740 out of the 3252 listings on realtor.com. Ran it again with the same input and it gave me 2680 listings. Checked the two outputs against each other and only about 2300 were duplicates, meaning the 500 missing listings are randomly skipped. Looking at the log my guess is it's not giving some pages enough time to load.

**Comment by tugkan** [comment]
Hey @jakekrafczyk 

Thank you very much for using our actor. Can you please send us the run IDs so that we can investigate it deeply?

Best

**Comment by jakekrafczyk** [comment]
Thanks for the follow up. The run IDs are CheW8ZQTP2PnY2895 and
pPSm0Hezl3sYfmpnu

Thanks,

Jake

**Comment by tugkan** [comment]
Hey @jakekrafczyk,

Thank you very much for the run IDs. We've investigated the issue, and Realtor seems to be providing different results in the pagination. This occasionally happens between the websites to block possible scraping techniques or fast data changes. Unfortunately, there are not many things to do on our side.

Please let us know if there is anything that we can help you with.
Best
