### ISSUE TITLE
Feature request: Ratings/Reviews/Recommendations

### ISSUE THREAD

**Issue by jbardnz** [tugkan/realtor-scraper#5]
Hi there,

I was wondering if you would consider either an upgrade to this actor, or creating a separate actor that scrapes the Ratings and reviews, as well as reccomendations from an agents profile. 

Here is an example profile https://www.realtor.com/realestateagents/56c7fbbc89a68901006e79d9

This agent has 47 Ratings and reviews and 14 Recommendations.

Cheers

**Comment by tugkan** [comment]
Hey @jbardnz !

Thank you very much for reaching out with this feature request. Our team is actively working on your needs and will let you know very soon regarding with the updates!

Best

**Comment by tugkan** [comment]
Hey @jbardnz !

We just implemented the feature of retrieving the agent profile. Currently, it supports providing all the information of an agent including reviews, ratings, bio, and many others. Unfortunately, listings of an agent feature are not yet supported but it is on our roadmap.

Best
