### ISSUE TITLE
Unable to scrape agent profiles

### ISSUE THREAD

**Issue by jbardnz** [tugkan/realtor-scraper#6]
Hi there,

A little while ago you made an update to this actor so I could scrape agent profiles. Here are a couple of examples of URLs:

https://www.realtor.com/realestateagents/569d0d2189a68901006bd943
https://www.realtor.com/realestateagents/56cb91e67e54f70100238403

However a recent update is giving me the below error while trying to scrape these profiles.
<img width="1208" alt="image (24)" src="https://user-images.githubusercontent.com/1628446/231727035-3aedd611-8b84-42c9-8b67-de9fb1c7edf4.png">

Here is the Github thread were you made the update: https://github.com/epctex/realtor-scraper/issues/3

**Comment by tugkan** [comment]
Hey @jbardnz !

Thank you very much for reaching out with this feature request. Our team is actively working on your needs and will let you know very soon regarding with the updates!

Best

**Comment by tugkan** [comment]
Hey @jbardnz !

We just implemented the feature of retrieving the agent profile. Currently, it supports providing all the information of an agent including reviews, ratings, bio, and many others. Unfortunately, listings of an agent feature are not yet supported but it is on our roadmap.

Best

**Comment by jbardnz** [comment]
Hey @tugkan,

Thanks for looking into this. This one is actually a bug report rather than a feature request. 

You can see in this ticket that you already added the ability to get all of the listing information for an agents profile for me: https://github.com/epctex/realtor-scraper/issues/3

I have been using this functionality on my project and it was working great up until a few weeks ago. 

Is it possible to restore this functionality as it is critical for my project :)
