### ISSUE TITLE
Realtor.com Floor Plans (multi-unit properties) not scraping

### ISSUE THREAD

**Issue by bryan-padstats** [tugkan/realtor-scraper#7]
We'd like to scrape the individual unit information (beds/baths/sqft/price/names) for apartment complexes on realtor.com

Here's some examples:
https://www.realtor.com/realestateandhomes-detail/1330-Wabank-Rd_Lancaster_PA_17603_M33869-29778
https://www.realtor.com/realestateandhomes-detail/5000-Foundry-Dr_Lancaster_PA_17601_M96685-88731
https://www.realtor.com/realestateandhomes-detail/816-N-Prince-St_Lancaster_PA_17603_M90968-65556

Beds & Baths etc do not show up for these scraped properties.

**Comment by tugkan** [comment]
Hey @bryan-padstats !

Thank you very much for reaching out and sorry for the late reply. We just integrated this functionality within a new flag called `includeFloorplans` (Include Floorplans). If you enable that switch on Apify Platform, or add `includeFloorplans:true` on your API requests, you will start retrieving the floorplans for the properties.

Please let me know if you need any further assistance,
Best
